export const mockData = {
  total: 300,
  page: '1',
  limit: '10',
  data: [
    {
      caseName: '2095',
      priority: 'High',
      assignee: 'Cort Bowller',
      description:
        'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
      status: 'Rejected',
      type: 'Clinical Chemistry',
      dateCreated: '12/16/2023',
      lastUpdated: '10/10/2023',
    },
    {
      caseName: '3401',
      priority: 'Low',
      assignee: 'Laura Morsley',
      description: 'Morbi porttitor lorem id ligula.',
      status: 'Rejected',
      type: 'Clinical Chemistry',
      dateCreated: '9/15/2023',
      lastUpdated: '9/9/2023',
    },
    {
      caseName: '0699',
      priority: 'Low',
      assignee: 'Lotty Karpeev',
      description:
        'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.',
      status: 'Rejected',
      type: 'Molecular Diagnostics',
      dateCreated: '1/10/2024',
      lastUpdated: '2/6/2024',
    },
    {
      caseName: '664',
      priority: 'High',
      assignee: 'Mildred Crimin',
      description: 'In sagittis dui vel nisl. Duis ac nibh.',
      status: 'Rejected',
      type: 'Microbiology',
      dateCreated: '8/6/2023',
      lastUpdated: '8/17/2023',
    },
    {
      caseName: '1453',
      priority: 'Low',
      assignee: 'Burr Duetschens',
      description:
        'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
      status: 'Rejected',
      type: 'Microbiology',
      dateCreated: '5/7/2024',
      lastUpdated: '11/19/2023',
    },
    {
      caseName: '4652',
      priority: 'Low',
      assignee: 'Starlin Orkney',
      description:
        'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
      status: 'Accepted',
      type: 'Microbiology',
      dateCreated: '5/27/2024',
      lastUpdated: '1/13/2024',
    },
    {
      caseName: '4132',
      priority: 'Low',
      assignee: "Lavinia O'Dee",
      description:
        'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.',
      status: 'Accepted',
      type: 'Endocrinology',
      dateCreated: '7/4/2023',
      lastUpdated: '4/7/2024',
    },
    {
      caseName: '9079',
      priority: 'Low',
      assignee: 'Sherlocke De Mitris',
      description:
        'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',
      status: 'Accepted',
      type: 'Urinalysis',
      dateCreated: '4/11/2024',
      lastUpdated: '7/7/2023',
    },
    {
      caseName: '7675',
      priority: 'High',
      assignee: 'Ruben Alastair',
      description:
        'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.',
      status: 'Accepted',
      type: 'Clinical Chemistry',
      dateCreated: '6/5/2024',
      lastUpdated: '7/8/2023',
    },
    {
      caseName: '7902',
      priority: 'Low',
      assignee: 'Abran Morman',
      description:
        'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
      status: 'Accepted',
      type: 'Clinical Chemistry',
      dateCreated: '6/13/2024',
      lastUpdated: '8/9/2023',
    },
  ],
};
